version: "3.9"
services:
  config-service:
    build:
      context: ./config-service
      dockerfile: Dockerfile
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - postgres
      - config-service
      - discovery-service
    environment:
      - CONFIG_SERVER_HOST=config-service
      - CONFIG_SERVER_PORT=8888
  item-service:
    build:
      context: ./item-service
      dockerfile: Dockerfile
    depends_on:
      - redis
      - config-service
      - discovery-service
    environment:
      - CONFIG_SERVER_HOST=config-service
      - CONFIG_SERVER_PORT=8888
  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - config-service
      - discovery-service
    environment:
      - CONFIG_SERVER_HOST=config-service
      - CONFIG_SERVER_PORT=8888
  admin-service:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    depends_on:
      - config-service
      - discovery-service
    environment:
      - CONFIG_SERVER_HOST=config-service
      - CONFIG_SERVER_PORT=8888
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - config-service
      - discovery-service
    environment:
      - CONFIG_SERVER_HOST=config-service
      - CONFIG_SERVER_PORT=8888
  postgres:
    image: "postgres:15.2"
    environment:
      - POSTGRES_PASSWORD=password
  redis:
    image: "redis:7.0.11"
  zookeeper:
    image: "confluentinc/cp-zookeeper:7.4.0"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  kafka:
    image: "confluentinc/cp-kafka:7.4.0"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
